# Generated by Django 4.2.27 on 2026-02-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_mocktest_studentmocktest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmocktest',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterUniqueTogether(
            name='studentmocktest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentmocktest',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
