# Generated by Django 4.2.27 on 2026-02-11 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_mockinterview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mockinterview',
            options={'ordering': ['-requested_date']},
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='requested_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
