# Generated by Django 4.2.27 on 2026-02-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_mockinterview_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=50)),
                ('agenda', models.TextField()),
                ('deliverables', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
